name: current_weather_design_system
description: "A tiny design system for Current Weather"
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  fonts:
    - family: CurrentWeatherIcons
      fonts:
        - asset: packages/current_weather_design_system/fonts/icons/CurrentWeatherIcons.ttf
    - family: Lato
      fonts:
        - asset: packages/current_weather_design_system/fonts/lato/lato_regular.ttf
          weight: 400
        - asset: packages/current_weather_design_system/fonts/lato/lato_bold.ttf
          weight: 500
